### ISSUE TITLE
Is it possible to run these packages on Ubuntu 18.04?

### ISSUE THREAD

**Issue by iamshyamganatra** [JdeRobot/IndustrialRobotics#1]
I was trying to setup these packages for that I checked the ros-wiki of [abb_experimental](http://wiki.ros.org/abb_experimental) and I saw that this is only for ROS-Kinetic and I am not able to install ROS-Kinetic on ubuntu 18.04.
Can I run it on Ubuntu 18.04 by any chance?

**Comment by diegomrt** [comment]
We haven't tried to run it on ROS-Melodic and Ubuntu 18.04. As you have noticed, the Gazebo models we use for the robotic arm (abb_experimental) and the gripper (robotiq_85) at the moment are compatible with ROS-Kinetic and Gazebo 7. 

However, give it a try on ROS-Melodic (i.e Gazebo 9) and let us know if it works.

**Comment by diegomrt** [comment]
Solved in #2
