### ISSUE TITLE
[melodic-devel] Compilation error in robotiq_85_driver package

### ISSUE THREAD

**Issue by diegomrt** [JdeRobot/IndustrialRobotics#3]
I'm getting the following error in the robotiq_85_driver package when compiling the new `melodic-devel` branch:

`Unknown CMake command "catkin_python_setup"`

It seems it can be easily fixed by editing the file "CMakeList.txt" in the robotiq_85_driver package and moving `find_package()` before `catkin_python_setup()`, as it is said [here](https://answers.ros.org/question/206512/is-catkin_python_setup-available-when-building-with-catkin_make_isolated/).

**Comment by sixer51** [comment]
I tested again with `catkin build` and get the same error. Your suggested solution can deal with it. Will make a pull request for this problem.
I didn't get this error because I used `catkin_make` to build my workspace, so that package relies on some other processed packages.

**Comment by diegomrt** [comment]
Solved in #4
